name: Test Rust Client

on:
  workflow_call:
    inputs:
      program_matrix:
        type: string
      git_ref:
        type: string

env:
  CACHE: true

jobs:
  test_sdk:
    name: Test
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: metaplex-foundation/actions/install-rust@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install Solana
        uses: metaplex-foundation/actions/install-solana@v1
        with:
          version: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Download program builds
        uses: actions/download-artifact@v4
        with:
          name: program-builds-${{ inputs.git_ref }}

      - name: Run tests
        shell: bash
        working-directory: configs/scripts/client
        run: RUST_LOG=error ./test-rust.sh
